name: Code Standards check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  php-cs-fixer:
    name: Run PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.0.0
        with:
          args: --config=.php-cs-fixer.dist.php --diff --dry-run

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: PHPStan
          uses: docker://oskarstark/phpstan-ga
          with:
              args: analyze src/ --level=5

  psalm:
    name: Psalm Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          security_analysis: true
