name: Psalm Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  psalm:
    name: Psalm Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          security_analysis: true

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: PHPStan
          uses: docker://oskarstark/phpstan-ga
          with:
              args: analyze src/ --level=5