name: Code Standards check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.0.0
        with:
          args: --config=.php-cs-fixer.dist.php --diff --dry-run

  analysis:
    name: PHP Code static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, phpstan, psalm, symfony

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Install phpunit
        run: bin/phpunit --version

      - name: PHPStan
        run: phpstan analyse -c phpstan.neon.dist --error-format=github

      - name: Psalm
        run: psalm --config=psalm.xml --output-format=github

      - name: Psalm security
        run: psalm --config=psalm.xml --output-format=github --taint-analysis

      - name: Check vendors security vulnerabilities
        run: symfony check:security

  analysis2:
    name: PHP Code static analysis 2
    runs-on: ubuntu-latest
    steps:
        - name: PHPStan
          runs-on: ubuntu-latest
          steps:
              - name: Checkout code
                uses: actions/checkout@v2

              - name: PHPStan
                uses: docker://oskarstark/phpstan-ga
                with:
                    args: analyze src/ --level=5

        - psalm:
          name: Psalm Security Scan
          runs-on: ubuntu-latest
          steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Psalm
              uses: docker://vimeo/psalm-github-actions
              with:
                security_analysis: true
