name: New Code Standards check

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  analysis:
    name: PHP Code static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, phpstan, psalm, symfony

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      # - name: Install phpunit
      #   run: bin/phpunit --version

      - name: PHPStan
        run: phpstan analyse -c phpstan.neon.dist --error-format=github

      - name: Psalm
        run: psalm --config=psalm.xml --output-format=github

      - name: Psalm security
        run: psalm --config=psalm.xml --output-format=github --taint-analysis

      - name: Check vendors security vulnerabilities
        run: symfony check:security